#Thông tin sinh viên:

Họ tên: Huỳnh Võ Ngọc Thanh

MSSV: 21520449

#Bài 4: Sử dụng các thư viện Machine Learning (Sklearn hoặc Skorch) thực thi lại 3 phương pháp Linear Regression, Logistic Regression và Softmax Regression.

In [1595]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import log_loss
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.metrics import accuracy_score, classification_report

import warnings
warnings.filterwarnings('ignore')

#Linear Regression method:

In [1596]:
data = pd.read_csv("/content/drive/MyDrive/DS102 TH/Lab3/housing.csv")

In [1597]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [1598]:
data.isna().sum(axis="index")

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [1599]:
data = data.dropna()

In [1600]:
data.duplicated().any()

False

In [1601]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [1602]:
data = data.drop(['ocean_proximity'], axis=1)
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0  
4       565.0       259.0         3.8462            342200.0

In [1603]:
X = data.drop('median_house_value', axis=1)
y = data['median_house_value']

In [1604]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [1605]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [1606]:
X_train

array([[7.03187251e-01, 1.61530287e-01, 1.17647059e-01, ...,
        3.73609126e-02, 6.93964808e-02, 2.76320327e-01],
       [2.38047809e-01, 4.87778959e-01, 4.90196078e-01, ...,
        3.92387679e-04, 4.93339911e-04, 1.00000000e+00],
       [4.52191235e-01, 4.52709883e-01, 5.49019608e-01, ...,
        3.47263096e-02, 8.86367374e-02, 2.13507400e-01],
       ...,
       [5.85657371e-01, 1.99787460e-01, 4.70588235e-01, ...,
        4.93287368e-02, 8.33744450e-02, 3.30257514e-01],
       [2.45019920e-01, 4.98405951e-01, 3.72549020e-01, ...,
        8.66335940e-02, 1.54579839e-01, 5.30344409e-01],
       [1.97211155e-01, 5.60042508e-01, 4.90196078e-01, ...,
        1.26909386e-01, 1.58033218e-01, 1.57997821e-01]])

In [1607]:
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)

LinearRegression()

In [1608]:
y_pred = linear_reg.predict(X_test)
y_pred

array([141888.54020848, 316900.78842465, 190807.02284247, ...,
       460260.69644416, 313206.39446276, 230016.70146241])

In [1609]:
RMSE = mean_squared_error(y_test, y_pred, squared=False)
print(f'RMSE =  {RMSE}')

RMSE =  69341.54057727774


#Logistic Regression method:

In [1611]:
data = pd.read_csv("/content/drive/MyDrive/DS102 TH/Lab3/data.csv", sep=";")
data.head()

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 37 columns]

In [1612]:
data.isna().sum(axis="index")

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance\t                      0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrol

In [1613]:
data = data.dropna()

In [1614]:
data.duplicated().any()

False

In [1615]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance	                     4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64  
 8   Mother's qualification                          4424 non-null   int64  
 9   Father's qualification                   

In [1616]:
def LabelEncoder (val:str) -> int:
  if val=="Enrolled" or val=="Dropout":
    return 0

  return 1

In [1617]:
data["Target"] = data["Target"].apply(LabelEncoder)
data.head()

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP  Target  
0             1.4  1.74       0  
1            -0.3  0.79       1  
2             1.4  1.74       0  
3            -0.8 -3.12       1  
4            -0.3  0.79       1  

[5 rows x 37 columns]

In [1618]:
X = data.drop('Target', axis=1)
y = data['Target']

In [1619]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [1620]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [1621]:
X_train

array([[0.        , 0.        , 0.11111111, ..., 0.37209302, 0.48888889,
        0.7661823 ],
       [0.        , 0.        , 0.11111111, ..., 0.91860465, 0.8       ,
        0.        ],
       [0.        , 0.28571429, 0.11111111, ..., 0.        , 0.75555556,
        0.57859974],
       ...,
       [0.        , 0.        , 0.11111111, ..., 1.        , 0.24444444,
        0.41479524],
       [0.        , 0.67857143, 0.11111111, ..., 0.40697674, 0.31111111,
        0.80317041],
       [0.        , 0.75      , 0.11111111, ..., 0.91860465, 0.8       ,
        0.        ]])

In [1622]:
logistic_reg = LogisticRegression(solver='lbfgs', max_iter=100)
logistic_reg.fit(X_train, y_train)

LogisticRegression()

In [1623]:
y_prob = logistic_reg.predict_proba(X_test)
y_prob

array([[0.24725633, 0.75274367],
       [0.24214666, 0.75785334],
       [0.52162334, 0.47837666],
       ...,
       [0.02841105, 0.97158895],
       [0.71894593, 0.28105407],
       [0.91143406, 0.08856594]])

In [1624]:
y_pred = logistic_reg.predict(X_test)

In [1625]:
loss = log_loss(y_test, y_prob)
print('Value of the loss function:', loss)

Value of the loss function: 0.3583899366326791


In [1626]:
acc = accuracy_score(y_test, y_pred)
print('Accuracy of Logistic Regression:', acc)

Accuracy of Logistic Regression: 0.8508474576271187


#Softmax Regression method:

In [1674]:
data = pd.read_csv("/content/drive/MyDrive/DS102 TH/Lab3/data.csv", sep=";")
data.head()

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 37 columns]

In [1675]:
data.isna().sum(axis="index")

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance\t                      0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrol

In [1676]:
data = data.dropna()

In [1677]:
data.duplicated().any()

False

In [1678]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance	                     4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64  
 8   Mother's qualification                          4424 non-null   int64  
 9   Father's qualification                   

In [1679]:
def LabelEncoder (val:str) -> int:
  if val=="Enrolled":
    return 0
  elif val=="Dropout":
    return 1
  return 2

In [1680]:
data["Target"] = data["Target"].apply(LabelEncoder)
data.head()

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP  Target  
0             1.4  1.74       1  
1            -0.3  0.79       2  
2             1.4  1.74       1  
3            -0.8 -3.12       2  
4            -0.3  0.79       2  

[5 rows x 37 columns]

In [1681]:
X = data.drop('Target', axis=1)
y = data['Target']

In [1682]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [1683]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [1684]:
X_train

array([[-0.29508811, -1.00486126,  0.19566257, ...,  0.4247424 ,
         1.78655742, -0.75212293],
       [-0.29508811, -1.00486126, -0.56028703, ..., -0.81453086,
        -1.46783146, -1.37811931],
       [-0.29508811, -1.00486126, -0.56028703, ..., -0.17611736,
        -0.45535492,  0.88781125],
       ...,
       [ 4.75805786,  1.178551  , -0.56028703, ...,  0.4247424 ,
         1.78655742, -0.75212293],
       [-0.29508811, -0.20044621, -0.56028703, ...,  0.87538723,
        -1.10623269,  0.34557494],
       [-0.29508811, -0.08552978,  0.19566257, ...,  0.87538723,
        -1.10623269,  0.34557494]])

In [1685]:
sm_reg = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=100)
sm_reg.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

In [1686]:
y_proba = sm_reg.predict_proba(X_test)
y_proba

array([[0.07852802, 0.0206505 , 0.90082148],
       [0.20317326, 0.30019427, 0.49663247],
       [0.15226659, 0.84655995, 0.00117346],
       ...,
       [0.03419622, 0.00880431, 0.95699947],
       [0.58897053, 0.19546052, 0.21556895],
       [0.33688505, 0.59104167, 0.07207328]])

In [1687]:
y_pred = sm_reg.predict(X_test)

In [1688]:
loss = log_loss(y_test, y_proba)
print('Value of the loss function:', loss)

Value of the loss function: 0.5505450551954074


In [1689]:
acc = accuracy_score(y_test, y_pred)
print('Accuracy of Softmax Regression:', acc)

Accuracy of Softmax Regression: 0.7819209039548023
